config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "chatroom#index"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"

  post "/message", to: "messages#create"

  get '/users', to: 'users#index'


  mount ActionCable.server, at: '/cabel'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  validates :body, presence: true, length: { minimum: 1, maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages, dependent: :destroy

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :logged_in?
  def logged_in?
    !!current_user
  end

  def redirect_if_logged_in
    redirect_to root_path if logged_in?
  end

  def require_user
    if !logged_in?
      flash[:error] = "you must be looged in.."
      redirect_to login_path
    end
    @user = current_user
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  def index
    redirect_to login_path unless logged_in?
    @messages = Message.all
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController 
  before_action :require_user, only: [:create]

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast("chatroom_channel", { message: render_message(message) })
    end
  end

  private 
  def message_params
    params.require(:message).permit(:body)
  end

  def render_message(message)
    render(partial: 'message', locals: { message: message })
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_logged_in, only: [:new, :create]

  def new
  end

  def create
    session_params = params[:session]
    username_param = session_params[:username]
    user = User.find_by(username: username_param)

    if user 
      password_param = session_params[:password]
      if user.authenticate(password_param)
        # authenticated
        session[:user_id] = user.id
        flash[:success] = "Welcome back #{user.username}!"
        redirect_to root_path
      else
        flash.now[:error] = "Invalid password"
        render 'new', status: :unauthorized
      end
    else
      flash.now[:error] = "Invalid login details"
      render 'new', status: :not_found
    end
  end

  def destroy
    if logged_in?
      session[:user_id] = nil
      flash[:success] = "user logged out successfully"
    else
      flash[:error] = "no logged in session found."
    end
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_logged_in, only: [:new, :create]

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "Welcome #{@user.username}, you have successfuly signed up."
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'new', status: :bad_request
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular blue comment alternate icon"></i>
  Say something
</h4>

<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message-container">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
         <%= form_for(@message, url: message_path, class: "ui reply form", remote: true) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body, placeholder: "Hey!", id: "message-input" %>
              <%= f.button '<i class="bordered inverted blue edit icon"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui fluid card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <%= link_to "Home" ,root_path ,class: "item" %>
          <%= link_to "Messages" ,root_path ,class: "item" %>
          <%= link_to "Friends" ,users_path ,class: "item" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |type, msg| %>
  <div class="ui <%= type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= msg %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui small inverted menu">
  <%= link_to "Chatroon", root_path, class: "item" %>
  <a class="item">
    Messages
  </a>
  <div class="right menu">
    <div class="ui dropdown item">
      Account <i class="dropdown icon"></i>
      <div class="menu">
        <% if logged_in?%>
          <%= link_to "Logout", logout_path, data: { turbo_method: :delete }, class: "item" %>
        <% else %>
          <%= link_to "Login", login_path, class: "item" %>
          <%= link_to "Signup", signup_path, class: "item" %>
        <% end %>
      </div>
    </div>
    <div class="item">
      <% if logged_in?%>
        <%= link_to "Logout", logout_path, data: { turbo_method: :delete }, class: "ui red button" %>
      <% else %>
        <%= link_to "Signup", signup_path, class: "ui primary button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="ui container">
      <%= render "layouts/navigation" %>
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary"><em><%= message.user.username %></em>: <%= message.body%></div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if resource.errors.any? %>
  <div class="ui error message transition" >
    <i class="close icon"></i>
    <h4 class="alert-heading">The following errors occured</h4>
    <div class="ui horizontal divider"></div>
    <% resource.errors.full_messages.each do |msg| %>
      <div class="header">
        <%= msg %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_welcome_message.html.erb
<h2 class="ui center aligned header">Welcome to MessageMe - a complete Chat App</h2>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="ui celled table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Joined Date</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.username %></td>
        <td><%= user.created_at.strftime("%B %d, %Y") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<%= render "shared/welcome_message" %>

<h4 class="ui center aligned medium icon header">
  <i class="circular blue power off icon"></i>
  Signup to continue
</h4>

<div class="ui placeholder segment">
  <div class="ui two column very relaxed stackable grid">
    <div class="column">
      <%= render "shared/errors", resource: @user %>
      <%= form_with(model: @user, url: signup_path, class: "ui form", local: true) do |f| %>
        <div class="field">
          <label>Username</label>
          <div class="ui left icon input">
            <%= f.text_field :username, placeholder: "Username" %>
            <i class="user icon"></i>
          </div>
        </div>
        <div class="field">
          <label>Password</label>
          <div class="ui left icon input">
            <%= f.password_field :password, placeholder: "Entrer your password" %>
            <i class="lock icon"></i>
          </div>
        </div>
        <div class="">
          <%= f.submit "Signup", class: "ui blue submit button" %>
        </div>
    <% end %>
      </div>
    <div class="middle aligned column">
      <div class="ui big button">
        <%= link_to '<i class="signup icon"></i> Login'.html_safe , login_path %>
      </div>
    </div>
  </div>
  <div class="ui vertical divider">Or</div>
</div>